/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public String getGreeting() {
        return "Hi";
    }

    public String getFarewell() {
      return "Bye";
    }
}
