/*
 * This Java source file was generated by the Gradle 'init' task.
 */

 import spock.lang.Specification


 class AppSpec extends Specification {
   def "getGreeting"(){
    expect: new App().getGreeting() == 'Hi'
  }
   def "getGreetingFail"(){
    expect: new App().getGreeting() == 'Hiii'
  }
 }
