/*
 * This Java source file was generated by the Gradle 'init' task.
 */

 import spock.lang.Specification


 class AppSpec extends Specification {
   def "The Greeting"(){
    expect: new App().getGreeting() == 'Hi'
  }
   def "The Farewell"(){
   setup: " lets see its value"
    expect: 
    new App().getFarewell() == 'Bye'
  }
 }
